trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    terraform validate
  displayName: 'Run terraform validate'
