trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: charleszipp.azure-pipelines-tasks-terraform.terraform-installer@0
  inputs:
    terraformVersion: 'latest'

- task: charleszipp.azure-pipelines-tasks-terraform.terraform@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform'

- task: charleszipp.azure-pipelines-tasks-terraform.terraform@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/terraform'
