trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Terraform..."
    wget https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
    unzip terraform_1.4.6_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
  displayName: 'Install Terraform'

- script: |
    terraform init
  displayName: 'Initialize Terraform'

- script: |
    terraform validate
  displayName: 'Validate Terraform'
